"""add review_records and operation_logs

Revision ID: 0c8ad2218e8f
Revises: fe9f80d40aff
Create Date: 2026-05-22 10:49:27.408042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c8ad2218e8f'
down_revision: Union[str, None] = 'fe9f80d40aff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
